version: "3.8"

services:

  redis:
    image: redis/redis-stack
    restart: unless-stopped
    env_file: .env
    ports:
      - $REDIS_SERVER_PORT:6379
      - $REDIS_INSIGHT_PORT:8001
    volumes:
      - redis-data:/data

  ad-selector:
    depends_on:
      - redis
    build: .
    restart: on-failure
    env_file: .env
    ports:
      - $SERVER_PORT:8080
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - selector-plans:/plans

volumes:
  redis-data:
  selector-plans:


